var figure = {
    "frames": [],
    "layout": {
        "autosize": true,
        "yaxis": {
            "range": [
                -11.11111111111111,
                11.11111111111111
            ],
            "type": "linear",
            "autorange": true,
            "title": "Linguistic Score"
        },
        "title": "Some Fake Plot",
        "breakpoints": [],
        "xaxis": {
            "range": [
                0,
                42
            ],
            "type": "category",
            "autorange": true,
            "title": "Date of Speech"
        },
        "hovermode": "closest"
    },
    "data": [
        {
            "autobinx": true,
            "uid": "77b576",
            "ysrc": "mlake900:2:880ff0",
            "textsrc": "mlake900:2:b05c67",
            "name": "Column 1",
            "xsrc": "mlake900:2:04dfad",
            "text": [
                "Title",
                "ut lacus. Nulla tincidunt, neque vitae",
                "habitant morbi tristique senectus et netus",
                "Nulla tincidunt, neque vitae semper egestas,",
                "lectus justo eu arcu. Morbi sit",
                "id risus quis diam luctus lobortis.",
                "facilisi. Sed neque. Sed eget lacus.",
                "pede nec ante blandit viverra. Donec",
                "morbi tristique senectus et netus et",
                "et magnis dis parturient montes, nascetur",
                "tempor erat neque non quam. Pellentesque",
                "lectus. Nullam suscipit, est ac facilisis",
                "ac libero nec ligula consectetuer rhoncus.",
                "vitae, sodales at, velit. Pellentesque ultricies",
                "leo. Cras vehicula aliquet libero. Integer",
                "Vivamus rhoncus. Donec est. Nunc ullamcorper,",
                "Nulla eget metus eu erat semper",
                "consequat nec, mollis vitae, posuere at,",
                "fringilla ornare placerat, orci lacus vestibulum",
                "Maecenas ornare egestas ligula. Nullam feugiat",
                "Sed pharetra, felis eget varius ultrices,",
                "amet ornare lectus justo eu arcu.",
                "eu tellus eu augue porttitor interdum.",
                "est, mollis non, cursus non, egestas",
                "gravida. Aliquam tincidunt, nunc ac mattis",
                "eleifend egestas. Sed pharetra, felis eget",
                "sociis natoque penatibus et magnis dis",
                "aptent taciti sociosqu ad litora torquent",
                "lectus sit amet luctus vulputate, nisi",
                "Vestibulum accumsan neque et nunc. Quisque",
                "quam vel sapien imperdiet ornare. In",
                "Duis ac arcu. Nunc mauris. Morbi",
                "non lorem vitae odio sagittis semper.",
                "vestibulum massa rutrum magna. Cras convallis",
                "porttitor interdum. Sed auctor odio a",
                "a felis ullamcorper viverra. Maecenas iaculis",
                "Nam interdum enim non nisi. Aenean",
                "id, mollis nec, cursus a, enim.",
                "Quisque purus sapien, gravida non, sollicitudin",
                "lorem eu metus. In lorem. Donec",
                "Sed molestie. Sed id risus quis",
                "Class aptent taciti sociosqu ad litora",
                "et ipsum cursus vestibulum. Mauris magna.",
                "Duis risus odio, auctor vitae, aliquet",
                "Proin vel nisl. Quisque fringilla euismod",
                "ipsum ac mi eleifend egestas. Sed",
                "tempor, est ac mattis semper, dui",
                "ac, fermentum vel, mauris. Integer sem",
                "ultricies sem magna nec quam. Curabitur",
                "tellus. Aenean egestas hendrerit neque. In",
                "nibh vulputate mauris sagittis placerat. Cras",
                "varius ultrices, mauris ipsum porta elit,",
                "cursus in, hendrerit consectetuer, cursus et,",
                "felis. Donec tempor, est ac mattis",
                "enim nec tempus scelerisque, lorem ipsum",
                "quis urna. Nunc quis arcu vel",
                "bibendum. Donec felis orci, adipiscing non,",
                "egestas ligula. Nullam feugiat placerat velit.",
                "sodales elit erat vitae risus. Duis",
                "velit. Sed malesuada augue ut lacus.",
                "Cras lorem lorem, luctus ut, pellentesque",
                "scelerisque neque sed sem egestas blandit.",
                "auctor non, feugiat nec, diam. Duis",
                "amet nulla. Donec non justo. Proin",
                "faucibus. Morbi vehicula. Pellentesque tincidunt tempus",
                "mi tempor lorem, eget mollis lectus",
                "ante bibendum ullamcorper. Duis cursus, diam",
                "Curabitur vel lectus. Cum sociis natoque",
                "pede ac urna. Ut tincidunt vehicula",
                "Fusce aliquam, enim nec tempus scelerisque,",
                "in faucibus orci luctus et ultrices",
                "Phasellus at augue id ante dictum",
                "nec urna et arcu imperdiet ullamcorper."
            ],
            "y": [
                "Linguistic Scale",
                "-9",
                "6",
                "-4",
                "3",
                "9",
                "3",
                "6",
                "4",
                "5",
                "7",
                "-3",
                "4",
                "10",
                "2",
                "-10",
                "-6",
                "-7",
                "8",
                "-8",
                "-5",
                "8",
                "0",
                "2",
                "-2",
                "-7",
                "-10",
                "-8",
                "5",
                "-3",
                "-1",
                "-5",
                "-6",
                "-2",
                "9",
                "10",
                "-4",
                "7",
                "1",
                "-9",
                "-1",
                "1",
                "0"
            ],
            "x": [
                "Date",
                "3/11/14",
                "3/20/14",
                "5/25/14",
                "6/19/14",
                "7/4/14",
                "7/6/14",
                "9/1/14",
                "9/10/14",
                "9/14/14",
                "10/10/14",
                "12/11/14",
                "12/16/14",
                "1/5/15",
                "1/17/15",
                "2/16/15",
                "3/26/15",
                "5/5/15",
                "8/20/15",
                "9/11/15",
                "11/8/15",
                "11/17/15",
                "11/18/15",
                "11/24/15",
                "11/26/15",
                "1/6/16",
                "1/14/16",
                "2/4/16",
                "6/8/16",
                "6/15/16",
                "6/19/16",
                "7/19/16",
                "8/4/16",
                "8/13/16",
                "8/15/16",
                "8/16/16",
                "8/26/16",
                "9/3/16",
                "9/16/16",
                "10/4/16",
                "10/5/16",
                "2/9/17",
                "2/10/17"
            ],
            "autobiny": true,
            "type": "scatter",
            "mode": "lines"
        }
    ]
}